#!/bin/sh

if [ "`whoami`"=="boinc" ]; then
	# Setup environment
	echo "${GUI_RPC_AUTH}" > /etc/boinc-client/gui_rpc_auth.cfg

	cat > "${HOME}/.boinctui.cfg" <<- END
	<boinctui_cfg>
		<server>
			<host>localhost</host>
			<pwd>${GUI_RPC_AUTH}</pwd>
			<port>31416</port>
			<hostid>localhost</hostid>
		</server>
		<version>2.7.0</version>
		<transparent_background>1</transparent_background>
	</boinctui_cfg>
	END

	if [ "$0"=="/bin/sh" ] && [ -z "$*" ]; then
		# This makes boinctui appear in Docker Desktop on the Exec tab
		boinctui
	fi
fi

test -n "$*" && exec "$@"
