#!/bin/sh

if [ "`whoami`"=="boinc" ]; then
	# Setup environment
	echo "${GUI_RPC_AUTH}" > /etc/boinc-client/gui_rpc_auth.cfg

	[ -n "${CPU_SCHEDULING_PERIOD_MINUTES}" ] && export PREF_CPU_SCHEDULING_PERIOD_MINUTES="${CPU_SCHEDULING_PERIOD_MINUTES}"
	[ -n "${CPU_USAGE_LIMIT}" ] && export PREF_CPU_USAGE_LIMIT="${CPU_USAGE_LIMIT}"
	[ -n "${HOST_VENUE}" ] && export PREF_HOST_VENUE="${HOST_VENUE}"
	[ -n "${MAX_NCPUS_PCT}" ] && export PREF_MAX_NCPUS_PCT="${MAX_NCPUS_PCT}"
	PREFS_OVERRIDE_FILE="/var/lib/boinc-client/global_prefs_override.xml"
	echo "<global_preferences>" > "${PREFS_OVERRIDE_FILE}"
	env | egrep -o '^PREF_[^=]+' | while read PREF; do
		KEY="$(echo "${PREF#PREF_}" | tr '[:upper:]' '[:lower:]')"
		eval VALUE="\${$PREF}"
		echo "<${KEY}>$([ "${VALUE}" = "none" ] || echo "${VALUE}")</${KEY}>" >> "${PREFS_OVERRIDE_FILE}"
	done
	[ -n "${GLOBAL_PREFERENCES_XML}" ] && echo "${GLOBAL_PREFERENCES_XML}" >> "${PREFS_OVERRIDE_FILE}"
	echo "</global_preferences>" >> "${PREFS_OVERRIDE_FILE}"

	cat > "/var/lib/boinc-client/.boinctui.cfg" <<- END
	<boinctui_cfg>
		<server>
			<host>localhost</host>
			<pwd>${GUI_RPC_AUTH}</pwd>
			<port>31416</port>
			<hostid>docker</hostid>
		</server>
		<version>2.7.0</version>
		<transparent_background>1</transparent_background>
	</boinctui_cfg>
	END

	cp -rn /etc/skel/. /var/lib/boinc-client/
	if [ ! -f "/var/lib/boinc-client/.vimrc" ]; then
		cat > "/var/lib/boinc-client/.vimrc" <<- END
		runtime! debian.vim
		set mouse=a
		map <Tab> :tabnext<CR>
		map <S-Tab> :tabprevious<CR>
		END
	fi

	if [ "$0"=="/bin/sh" ] && [ -z "$*" ]; then
		# This makes boinctui appear in Docker Desktop on the Exec tab
		boinctui
		bash -l && exit || echo -n "\n[$0] `whoami`@`hostname`"
	fi
fi

test -n "$*" && exec "$@"
